### ISSUE TITLE
Compatibility with "dash-to-panel"

### ISSUE THREAD

**Issue by xisberto** [bellini666/gnome-shell-notifications-alert#33]
There's an other extension https://github.com/jderose9/dash-to-panel which changes the position and spacing of the top bar and the clock.

When using dash-to-panel, the color change makes also the spacing arround the clock change. I have tried to configure the dash-to-panel spacing options, but my clock keeps "dancing" while changing colors.

**Comment by Pl4yeR** [comment]
I suffer from this too. The weird thing is that I have 2 computers with the same setup and only one is suffering this, the other is just fine.

Also, when I disable and then reenable the extensions from gnome tweak tool this bug disappear until next reboot :S

**Comment by s4bba7** [comment]
I've asked dash-to-panel developers about this bug and this is their answer:
https://github.com/jderose9/dash-to-panel/issues/160#event-1092894910

**Comment by hackedbellini** [comment]
@s4bba7 interesting... Well, I'm not having much time these days to do that change, but I'm (and always will be) accepting contributions. Just send me a PR and if it is ok I'll merge it and release a new version on ego.

**Comment by Baltix** [comment]
@hackedbellini It's very easy to correct in Notifications Alert: Currently when your extension assigns the color style, it removes the style that this panel has added. It could be updated to append to the existing style instead:
`let userStyle = "color: " + settings.get_string(SETTING_COLOR);`

**Comment by hackedbellini** [comment]
@Baltix that's good to know. I'm a little busy those days to do the change, but if you want you can do it and open a PR and I'll gladly merge it!
