### ISSUE TITLE
Providing new strings to translate (for new feature background color)

### ISSUE THREAD

**Issue by Etamuk** [bellini666/gnome-shell-notifications-alert#49]
Hello :-)

Happy to see the new option for changing background color. 
Can you please provide the new strings to translate in the pot file?

Maybe the new string "Use alert color" should be changed to "Use alert font color" and "Alert color" to "Alert font color". 

Best regards from germany :-)

**Comment by bellini666** [comment]
Hi @Etamuk .

I like you idea and just implemented it. If you want you can update the german translation and I'll release a new version as soon as I merge it!

Best regards from Brazil :)

**Comment by Etamuk** [comment]
Hello @bellini666 
I have translated the new strings and copied it into the local extensions folder on my system to test it. 
These strings are not translated: 
These are: 
```
Alert font color
Use alert font color
Use the alert font color for alert blinks (default: ON)
```
These strings are shown with the old string:
```
Alert color
Use alert color
```
Can you please take a look at this, when you have some time?

Thank you

**Comment by bellini666** [comment]
@Etamuk sorry for the delay, I've been very busy those days.

Regarding those:

```
Alert font color
Use alert font color
Use the alert font color for alert blinks (default: ON)
```

I see that they are all for translation. Maybe when you copied it to your extensions folder you forgot to compile the translations. You need to do a `make locale` to do that. You can run a `make install` which will run the `locale` rule, then the `zip-file` rule and unzip everything in your extensions folder.

```
Alert color
Use alert color
```

Those strings are not in use anymore. Maybe it is a side-effect of the previous issue?

**Comment by Etamuk** [comment]
Hello @bellini666 
Sorry, 
It seems I made some little mistakes with the new translations. Especially some lines were marked as "fuzzy" in translation file. I did a complete rework now and I hope it's working now. 

Best regards :-)
