### ISSUE TITLE
Extensión doesn't work in GNOME 45

### ISSUE THREAD

**Issue by fprietog** [bellini666/gnome-shell-notifications-alert#59]
In GNOME 45 (Ubuntu 23.10) the extension doesn't start showing this error in the journal:
```
JS ERROR: Extension notifications-alert-on-user-menu@hackedbellini.gmail.com: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0
```

**Comment by ChrisLauinger77** [comment]
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils

**Comment by fprietog** [comment]
@zweif ,
I just tested your pull request in GNOME 45 (Ubuntu 23.10). Everything went OK.

Thank you!
